"""create initial tables

Revision ID: 66cc6f7da368
Revises: f1bb9e381f9d
Create Date: 2025-01-28 18:16:19.307686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cc6f7da368'
down_revision = 'f1bb9e381f9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'date')
    # ### end Alembic commands ###
